---
- hosts: station
  become: true
  tasks:
    - name: Set timezone to Europe/Brussels
      community.general.timezone:
        name: Europe/Brussels
    # - name: Set NTP server to the one from UGent
    #   ansible.builtin.lineinfile:
    #     path: /etc/systemd/timesyncd.conf
    #     regexp: '^#NTP='
    #     line: "NTP=ntp.ugent.be"
    # - name: Enable ntp time sync
    #   ansible.builtin.systemd:
    #     daemon_reload: true
    #     name: systemd-time-wait-sync
    #     enabled: true
    #     state: started
    - name: Install base dependencies
      apt:
        name: [
          'zsh', 'git', 'htop', 'curl', 'vim', 'dnsutils', 'tmux',
          'gcc', 'build-essential',
          'python3-dev', 'python3-setuptools', 'python3-pip', 'python3-wheel',
          'acl', 'postgresql', 'libpq-dev', 'python3-psycopg2'
        ]
        update_cache: true
        install_recommends: false
      tags: ['db']
    - name: Set a hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"
    - name: Add a /etc/hosts entry for our hostname
      ansible.builtin.lineinfile:
        path: /etc/hosts
        insertafter: '^127\.0\.0\.1[ ]+localhost'
        line: "127.0.0.1   {{ inventory_hostname }}"
        owner: root
        group: root
        mode: '0644'
        create: true
    - name: Change password for pi user
      ansible.builtin.user:
        name: pi
        shell: /bin/bash
        state: present
        password: "{{ 'zeusisdemax' | password_hash('sha512') }}"
    - name: Install golang
      import_role:
        name: gantsign.golang
      tags: ['build']

    - name: Checkout the gonny repository
      ansible.builtin.git:
        repo: 'https://github.com/NuttyShrimp/gonny-the-station-chef.git'
        dest: '/gonny'
        version: 'master'

    # - name: Install go dependencies
    #   ansible.builtin.command:
    #     cmd: go mod download
    #     chdir: /gonny/
    - name: Built collector binary
      ansible.builtin.command:
        cmd: env GOROOT={{ golang_install_dir }} GOPATH=/root {{ golang_install_dir }}/bin/go build -o cmds/collector/main cmds/collector/main.go
        chdir: /gonny/
      tags: ['build']
    - name: Built spreader binary
      ansible.builtin.command:
        cmd: env GOROOT={{ golang_install_dir }} GOPATH=/root {{ golang_install_dir }}/bin/go build -o cmds/spreader/main cmds/spreader/main.go
        chdir: /gonny/
      tags: ['build']

    - name: Ensure postgresql is in a running state
      service:
        name: postgresql
        state: started
      register: postgresqlDetails
      until: postgresqlDetails.status.ActiveState == "active"
      retries: 15
      delay: 2
      tags: ['db']
    - name: Wait for postgres port to come up
      wait_for:
        port: 5432
      tags: ['db']
    - name: Create a new database with name "ronny"
      become: true
      become_user: postgres
      community.postgresql.postgresql_db:
        name: ronny
      tags: ['db']
    - name: Connect to ronny database, create ronny user, and grant access to database
      become: true
      become_user: postgres
      community.postgresql.postgresql_user:
        db: ronny
        name: ronny
        password: ronnydbpassword
        priv: "ALL"
      tags: ['db']
    - name: Copy systemd files
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "/etc/systemd/system/{{ item }}"
        owner: root
        group: root
        mode: '0644'
      loop:
        - gonny-collector.service
        - gonny-spreader.service
    - name: Enable systemd services
      ansible.builtin.systemd:
        daemon_reload: true
        name: "{{ item }}"
        enabled: true
        state: restarted
      loop:
        - gonny-collector
        - gonny-spreader

